### ISSUE TITLE
EDI syntax errors don't route to failure.

### ISSUE THREAD

**Issue by bpenelli** [mrcsparker/nifi-edireader-bundle#6]
2018-06-01 15:37:32,480 ERROR [Timer-Driven Process Thread-5] o.a.nifi.processors.edireader.EdiToXML EdiToXML[id=bca60008-0163-1000-e89a-ee6496b7cb79] TransformerException: com.berryworks.edireader.EDISyntaxException: Expected a simple token at segment 3, field 3
2018-06-01 15:37:32,480 ERROR [Timer-Driven Process Thread-5] o.a.nifi.processors.edireader.EdiToXML EdiToXML[id=bca60008-0163-1000-e89a-ee6496b7cb79] EdiToXML[id=bca60008-0163-1000-e89a-ee6496b7cb79] failed to process due to java.lang.IllegalStateException: StandardFlowFileRecord[uuid=048f3fa0-4189-4fcb-a4c1-ce9182e36afa,claim=StandardContentClaim [resourceClaim=StandardResourceClaim[id=1527876176823-20, container=default, section=20], offset=245291, length=485],offset=0,name=TRAC_BOES_000513891_20180530092200_994357562229589.txt,size=485] already in use for an active callback or an InputStream created by ProcessSession.read(FlowFile) has not been closed; rolling back session: {}
java.lang.IllegalStateException: StandardFlowFileRecord[uuid=048f3fa0-4189-4fcb-a4c1-ce9182e36afa,claim=StandardContentClaim [resourceClaim=StandardResourceClaim[id=1527876176823-20, container=default, section=20], offset=245291, length=485],offset=0,name=TRAC_BOES_000513891_20180530092200_994357562229589.txt,size=485] already in use for an active callback or an InputStream created by ProcessSession.read(FlowFile) has not been closed
        at org.apache.nifi.controller.repository.StandardProcessSession.validateRecordState(StandardProcessSession.java:3060)
        at org.apache.nifi.controller.repository.StandardProcessSession.validateRecordState(StandardProcessSession.java:3055)
        at org.apache.nifi.controller.repository.StandardProcessSession.transfer(StandardProcessSession.java:1854)
        at org.apache.nifi.processors.edireader.EdiToXML.lambda$null$0(EdiToXML.java:118)
        at org.apache.nifi.controller.repository.StandardProcessSession.write(StandardProcessSession.java:2571)
        at org.apache.nifi.processors.edireader.EdiToXML.lambda$onTrigger$1(EdiToXML.java:84)
        at org.apache.nifi.controller.repository.StandardProcessSession.read(StandardProcessSession.java:2175)
        at org.apache.nifi.controller.repository.StandardProcessSession.read(StandardProcessSession.java:2145)
        at org.apache.nifi.processors.edireader.EdiToXML.onTrigger(EdiToXML.java:84)
        at org.apache.nifi.processor.AbstractProcessor.onTrigger(AbstractProcessor.java:27)
        at org.apache.nifi.controller.StandardProcessorNode.onTrigger(StandardProcessorNode.java:1122)
        at org.apache.nifi.controller.tasks.ContinuallyRunProcessorTask.call(ContinuallyRunProcessorTask.java:147)
        at org.apache.nifi.controller.tasks.ContinuallyRunProcessorTask.call(ContinuallyRunProcessorTask.java:47)
        at org.apache.nifi.controller.scheduling.TimerDrivenSchedulingAgent$1.run(TimerDrivenSchedulingAgent.java:128)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by bpenelli** [comment]
I made a fix for this if you're interested.

**Comment by mrcsparker** [comment]
I am interested

Chris Parker

**Comment by bpenelli** [comment]
I forked the repository and applied the fix here: https://github.com/bpenelli/nifi-edireader-bundle
It appears the problem is related to routing the flowfile within a session read/write after an exception, because the streams aren't getting closed.
    On Sunday, June 10, 2018, 5:44:43 PM EDT, Chris Parker <notifications@github.com> wrote:  
 
 I am interested

Chris Parker

**Comment by mrcsparker** [comment]
I will check it out today. Thanks so much

Can you make a pull request?

**Comment by bpenelli** [comment]
Done.

**Comment by mrcsparker** [comment]
Merged your change.  Thanks for this
